apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-server-certs
  namespace: argocd
spec:
  secretName: argocd-server-tls
  issuerRef:
    name: letsencrypt-issuer
    namespace: default
    kind: ClusterIssuer
  commonName: argocd.ryanguild.localhost
  dnsNames:
    - argocd.ryanguild.localhost
    - www.argocd.ryanguild.localhost
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
