apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-server-certs
  namespace: default
spec:
  secretName: argocd-server-tls
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
  commonName: argocd.ryanguild.localhost
  dnsNames:
    - argocd.ryanguild.localhost
    - www.argocd.ryanguild.localhost
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
