apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: xyz
  namespace: argocd
spec:
  description: "Project for managing Sealed Secrets installation"
  # Source Repositories allowed for this project
  sourceRepos:
    - "*"
  # Cluster and namespace destinations this project can deploy to
  destinations:
    - namespace: xyz
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
  # Optionally, specify which kinds of cluster/namespaced resources are allowed
  # If you trust the chart fully, you can keep them broad:
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: xyz-apps
  namespace: argocd
spec:
  project: xyz
  sources:
  - repoURL: https://github.com/ryanguild/xyz-cluster.git
    targetRevision: main
    path: ngrok
  - repoURL: https://github.com/ryanguild/xyz-cluster.git
    targetRevision: main
    path: sealed-secrets
  - repoURL: https://github.com/ryanguild/xyz-cluster.git
    targetRevision: main
    path: keycloak
  - repoURL: https://github.com/ryanguild/xyz-cluster.git
    targetRevision: main
    path: hello
  destination:
    server: https://kubernetes.default.svc
    namespace: xyz
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: v1
kind: Namespace
metadata:
  name: xyz
---
apiVersion: v1
kind: Service
metadata:
  name: argocd-server
  namespace: xyz
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: argocd-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
