apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: xyz
  namespace: argocd
spec:
  description: "Project for managing Sealed Secrets installation"
  # Source Repositories allowed for this project
  sourceRepos:
    - "*"
  # Cluster and namespace destinations this project can deploy to
  destinations:
    - namespace: default
      server: https://kubernetes.default.svc
    - namespace: keycloak
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
    - namespace: kube-system
      server: https://kubernetes.default.svc
    - namespace: ngrok
      server: https://kubernetes.default.svc
  # Optionally, specify which kinds of cluster/namespaced resources are allowed
  # If you trust the chart fully, you can keep them broad:
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: xyz-apps
  namespace: argocd
spec:
  project: xyz
  sources:
    - repoURL: https://github.com/ryanguild/xyz-cluster.git
      targetRevision: main
      path: keycloak
    - repoURL: https://github.com/ryanguild/xyz-cluster.git
      targetRevision: main
      path: hello
    - repoURL: https://github.com/ryanguild/xyz-cluster.git
      targetRevision: main
      path: ngrok
    - repoURL: https://github.com/ryanguild/xyz-cluster.git
      targetRevision: main
      path: vault
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
