apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-apps
  namespace: argocd
spec:
  project: xyz
  sources:
  - repoURL: https://github.com/ryanguild/xyz-cluster.git
    targetRevision: main
    path: traefik
  - repoURL: https://github.com/ryanguild/xyz-cluster.git
    targetRevision: main
    path: ngrok
  - repoURL: https://github.com/ryanguild/xyz-cluster.git
    targetRevision: main
    path: sealed-secrets
  - repoURL: https://github.com/ryanguild/xyz-cluster.git
    targetRevision: main
    path: keycloak
  - repoURL: https://github.com/ryanguild/xyz-cluster.git
    targetRevision: main
    path: hello
  destination:
    server: https://kubernetes.default.svc
    namespace: xyz
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      