apiVersion: v1
data:
  admin.enabled: 'true'
  application.instanceLabelKey: argocd.argoproj.io/instance
  exec.enabled: 'false'
  server.rbac.log.enforce.enable: 'false'
  statusbadge.enabled: 'false'
  timeout.hard.reconciliation: 0s
  timeout.reconciliation: 180s
  url: https://argocd.ryanguild.localhost
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: default