apiVersion: networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argocd-http-route
  namespace: argocd
spec:
  parentRefs:
    - group: networking.k8s.io
      kind: Gateway
      name: localhost-gateway
      namespace: nginx
  rules:
    - matches:
        - path:
            type: Prefix
            value: /
      forwardTo:
        - serviceName: my-service
          port: 80