apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# 2) Optional common namespace or name prefix
namespace: default

helmCharts:
  - name: argocd
    releaseName: argocd
    includeCRDs: true
    version: 7.7.16
    repo: https://argoproj.github.io/argo-helm
    valuesFile: ./values.yaml

# 3) Patches to modify specific objects after the Helm chart is rendered
patches:
  - path: ./patches/argo-cm.yaml
    target:
      kind: ConfigMap
      # You can narrow down which ConfigMap to patch by name
      # name: my-helm-release-config  (example if you know the final name)
      # or by label selectors, etc.
# resources:
#   - ./resouces/gateway-routes.yaml
