apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# 2) Optional common namespace or name prefix
namespace: default

# 3) Patches to modify specific objects after the Helm chart is rendered
patches:
  - path: argocd/src/patches/argo-cm.yaml
    target:
      kind: ConfigMap
      # You can narrow down which ConfigMap to patch by name
      # name: my-helm-release-config  (example if you know the final name)
      # or by label selectors, etc.

resources:
  - argocd/arc/resouces/gateway-routes.yaml
