apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

helmCharts:
  - repo: https://argoproj.github.io/argo-helm
    name: argo-cd
    namespace: default
    releaseName: argocd
    valuesMerge: merge
    valuesInline:
      global:
        domain: argocd.ryanguild.localhost
      params:
        server.insecure: true

resources:
  - resources/**.yaml

patches:
  - path: patches/argocd-cm.yaml
