apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: localhost-gateway
  namespace: default
spec:
  gatewayClassName: nginx
  listeners:
    - allowedRoutes:
        namespaces:
          from: Same
      hostname: localhost
      name: same-namespace
      port: 80
      protocol: HTTP
    - hostname: localhost
      name: localhost
      port: 80
      protocol: HTTP
      routes:
        kind: HTTPRoute
        namespaces:
          from: All