apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: localhost-gateway
  namespace: default
spec:
  gatewayClassName: nginx
  listeners:
    - name: localhost
      protocol: HTTP
      port: 80
      hostname: localhost
      routes:
        kind: HTTPRoute
        namespaces:
          from: All