apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello
  namespace: argocd
spec:
  project: xyz
  sources:
  - repoURL: https://github.com/ryanguild/xyz-cluster.git
    path: hello/src
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: xyz
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
