apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/ryanguild/xyz-cluster.git'
    targetRevision: HEAD
    path: hello/src
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: hello
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true