apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: traefik-dashboard-http-route
  namespace: default
spec:
  parentRefs:
    - name: traefik-gateway
      namespace: default
  rules:
    - hostnames:
        - "traefik.ryanguild.localhost"
      backendRefs:
        - name: api@internal
          kind: TraefikService
      matches:
        - path:
            type: PathPrefix
            value: /
