apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: traefik-localhost-gateway
  namespace: default
spec:
  gatewayClassName: traefik
  listeners:
    - name: web
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: All
    - name: websecure
      port: 443
      protocol: HTTPS
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - name: traefik-localhost-tls
            namespace: default
  hostname: ryanguild.localhost
  addresses:
    - type: Hostname
      value: ryanguild.localhost
