apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik-localhost-tls
  namespace: default
spec:
  secretName: traefik-localhost-tls
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
  commonName: ryanguild.localhost
  dnsNames:
    - ryanguild.localhost
    - "*.ryanguild.localhost"
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
