apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: traefik-xyz-gateway
  namespace: default
spec:
  gatewayClassName: traefik
  listeners:
    - name: web
      port: 80
      protocol: HTTP
    - name: websecure
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - name: traefik-xyz-tls
            namespace: default
    - name: grpc
      port: 50051
      protocol: GRPC
  hostname: ryanguild.xyz
  addresses:
    - type: Hostname
      value: ryanguild.xyz
