apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
spec:
  project: xyz
  sources:
  - repoURL: registry-1.docker.io/bitnamicharts
    targetRevision: 24.3.1
    chart: keycloak
    # valuesObject:
    #   auth:
    #     existingSecret: keycloak-auth-secret
    #  postgresql:
    #    auth:
    #      existingSecret: keycloak-postgresql-secret
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: xyz
  syncPolicy:
    automated:
      prune: true
      selfHeal: true