apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
spec:
  project: xyz
  sources:
  - repoURL: https://charts.bitnami.com/bitnami
    targetRevision: "17.3.2"
    chart: keycloak
    valuesObject:
      httpRelativePath: "/keycloak"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: xyz
  syncPolicy:
    automated:
      prune: true
      selfHeal: true