apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
metadata:
  name: argocd-http-route
  namespace: default
spec:
  parentRefs:
    - name: traefik-gateway
  rules:
    - hostnames:
        - argocd.ryanguild.localhost
      backendRefs:
        - name: argocd-service
          port: 80
