apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: default
spec:
  project: xyz
  sources:
    # - repoURL: https://github.com/kubernetes-sigs/gateway-api.git
    #   targetRevision: v1.2.0
    #   path: config/crd/standard
    # - repoURL: https://github.com/kubernetes-sigs/gateway-api.git
    #   targetRevision: v1.2.0
    #   path: config/crd/experimental
    - repoURL: https://traefik.github.io/charts
      chart: traefik
      targetRevision: 34.1.0
      helm:
        releaseName: traefik
        valuesObject:
          providers:
            kubernetesGateway:
              enabled: true
              experimentalChannel: true
            kubernetesIngress:
              enabled: false
          gateway:
            enabled: true
            listeners:
              web:
                port: 8000
                protocol: HTTP
                namespacePolicy: All
                hostname: ryanguild.xyz
            #   websecure:
            #     port: 8443
            #     protocol: HTTPS
            #     namespacePolicy: All
            #     hostname: ryanguild.xyz
            #     certificateRef:
            #       name: traefik-xyz-tls
            #       namespace: default
            # localhost:
            #   port: 80
            #   protocol: HTTP
            #   namespacePolicy: All
            #   hostname: localhost
            # localhostsecure:
            #   port: 443
            #   protocol: HTTPS
            #   namespacePolicy: All
            #   hostname: localhost
            #   certificateRef:
            #     name: traefik-localhost-tls
            #     namespace: default

    - repoURL: https://github.com/ryanguild/xyz-cluster
      path: traefik/src
      targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 2
