apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: default
spec:
  project: xyz
  sources:
    # - repoURL: https://github.com/kubernetes-sigs/gateway-api.git
    #   targetRevision: v1.2.0
    #   path: config/crd/standard
    - repoURL: https://github.com/kubernetes-sigs/gateway-api.git
      targetRevision: v1.2.0
      path: config/crd/experimental
    - repoURL: https://traefik.github.io/charts
      chart: traefik
      targetRevision: 34.1.0
      helm:
        releaseName: traefik
        valuesObject:
          providers:
            kubernetesGateway:
              enabled: true
            kubernetesIngress:
              enabled: false
          gateway:
            enabled: true
            namespacePolicy: All
          ingressRoute:
            dashboard:
              # -- Create an IngressRoute for the dashboard
              enabled: true
              # -- Additional ingressRoute annotations (e.g. for kubernetes.io/ingress.class)
              annotations: {}
              # -- Additional ingressRoute labels (e.g. for filtering IngressRoute by custom labels)
              labels: {}
              # -- The router match rule used for the dashboard ingressRoute
              matchRule: Host(`traefik.ryanguild.localhost`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))
              # -- The internal service used for the dashboard ingressRoute
              services:
                - name: api@internal
                  kind: TraefikService
              # -- Specify the allowed entrypoints to use for the dashboard ingress route, (e.g. traefik, web, websecure).
              # By default, it's using traefik entrypoint, which is not exposed.
              # /!\ Do not expose your dashboard without any protection over the internet /!\
              entryPoints: ["traefik", "web", "websecure"]
              # -- Additional ingressRoute middlewares (e.g. for authentication)
              middlewares: []
              # -- TLS options (e.g. secret containing certificate)
              tls: {}
          metrics:
            addInternals: true
          tracing:
            addInternals: true

    # - repoURL: https://github.com/ryanguild/xyz-cluster
    #   path: traefik/src
    #   targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 2
