apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: default
spec:
  project: xyz
  sources:
    # - repoURL: https://github.com/kubernetes-sigs/gateway-api.git
    #   targetRevision: v1.2.0
    #   path: config/crd/standard
    - repoURL: https://github.com/kubernetes-sigs/gateway-api.git
      targetRevision: v1.2.0
      path: config/crd/experimental
    - repoURL: https://traefik.github.io/charts
      chart: traefik
      targetRevision: 33.2.1
      helm:
        releaseName: traefik
        valuesObject:
          providers:
            kubernetesGateway:
              enabled: true
            kubernetesIngress: 
              enabled: false
          gateway:
            enabled: true
            namespacePolicy: All
  #- repoURL: https://github.com/ryanguild/xyz-cluster
  #   path: traefik/src
  #   targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 2
