apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: xyz
  sources:
  - repoURL: https://traefik.github.io/charts
    chart: traefik
    targetRevision: 33.2.1
    helm:
      releaseName: traefik
      valuesObject:
        experimental:
          kubernetesGateway:
            enabled: true
        gateway:
          enabled: true
        gatewayClass:
          enabled: true

  # - repoURL: https://github.com/ryanguild/xyz-cluster
  #   path: traefik/src
  #   targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: xyz
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  revisionHistoryLimit: 2 