apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: xyz
  sources:
  - repoURL: https://traefik.github.io/charts
    chart: traefik
    targetRevision: 33.2.1
    helm:
      releaseName: traefik
      valuesObject:
        providers:
          kubernetesGateway:
            enabled: true
            experimentalChannel: true
          kubernetesIngress:
            enabled: false
        experimental:
          kubernetesGateway:
            enabled: true
        gateway:
          enabled: true
        gatewayClass:
          enabled: true
        ports:
          web:
            port: 80
            expose: true
            exposedPort: 80
            protocol: TCP
        ingressClass:
          enabled: false
        deployment:
          kind: Deployment
        logs:
          general:
            level: DEBUG
        installation:
          enabled: true
          createNamespace: true
          namespace: xyz
        crds:
          install: true
          allowNamespaceList:
            - xyz

  # - repoURL: https://github.com/ryanguild/xyz-cluster
  #   path: traefik/src
  #   targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: xyz
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  revisionHistoryLimit: 2 