apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  project: xyz
  sources:
  - repoURL: https://bitnami-labs.github.io/sealed-secrets
    chart: sealed-secrets
    targetRevision: 2.10.0
    helm:
      releaseName: sealed-secrets
      values: |
        fullnameOverride: sealed-secrets-controller
  - repoURL: https://github.com/RyanGuild/xyz-cluster.git
    path: sealed-secrets/src
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: xyz
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  revisionHistoryLimit: 2