apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: hello-http-route
spec:
  hostnames:
    - hello.ryanguild.xyz
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: ngrok-gateway
      namespace: ngrok
  rules:
    - backendRefs:
        - kind: Service
          name: hello-service
          namespace: hello
          port: 80
          