apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: hello-http-route
  namespace: hello
spec:
  gatewayClassName: ngrok
  listeners:
  - name: http-listener
    port: 80
    protocol: HTTP
    hostname: hello.ryanguild.xyz
  hostnames:
    - hello.ryanguild.xyz
  parentRefs:
    - name: ngrok
      namespace: ngrok
  rules:
    - matches:
      - path:
          type: PathPrefix
          value: /