apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ngrok
  namespace: argocd
spec:
  project: xyz
  sources:
  - repoURL: https://charts.ngrok.com
    chart: ngrok-operator
    targetRevision: 0.16.4
    helm:
      releaseName: ngrok
      values: |
        credentials:
          secret:
            name: ngrok-credentials
  # - repoURL: https://github.com/ryanguild/xyz-cluster
  #   path: ngrok/src
  #   targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  revisionHistoryLimit: 2 