apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ngrok
  namespace: argocd
spec:
  project: xyz
  sources:
  - repoURL: "https://charts.ngrok.com"
    chart: "ngrok-operator"
    targetRevision: "0.16.4"
    helm:
      releaseName: ngrok
      
  - repoURL: https://github.com/ryanguild/xyz-cluster.git
    path: ngrok/src
    targetRevision: main
  destination:
    server: "https://kubernetes.default.svc"
    namespace: xyz
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  revisionHistoryLimit: 2 