apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ngrok-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.ngrok.com/ngrok
    targetRevision: 0.17.0
    chart: ngrok-operator
  destination:
    server: https://kubernetes.default.svc
    namespace: ngrok
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true