apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ngrok-operator
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://charts.ngrok.com
    targetRevision: 0.17.0
    chart: ngrok-operator
    valuesObject:
      gateway:
        enabled: true
      ingress:
        enabled: false
  - repoURL: https://github.com/ryanguild/xyz-cluster.git
    targetRevision: main
    path: ngrok/src
  destination:
    server: https://kubernetes.default.svc
    namespace: ngrok
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true