apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ngrok
  namespace: argocd
spec:
  project: xyz
  source:
    repoURL: "https://charts.ngrok.com"
    chart: "ngrok-operator"
    targetRevision: "0.16.4"
    helm:
      releaseName: ngrok
      values: |
        credentials:
          apiKey:
            valueFrom:
              secretKeyRef:
                name: ngrok-apikey
                key: ngrok-apikey
          authtoken:
            valueFrom:
              secretKeyRef:
                name: ngrok-authentoken
                key: ngrok-authentoken
        
  destination:
    server: "https://kubernetes.default.svc"
    namespace: xyz
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  revisionHistoryLimit: 2 