apiVersion: v1
kind: Secret
metadata:
  name: ngrok-credentials
  namespace: default
type: Opaque
stringData:
  AUTHTOKEN: 2mRqvWIRuoSMGpQ8vxUfwkN317U_3MyGAXEQBds4NmQjhWdcJ
  API_KEY: 2r2W58Tcg1ojwDjwGcawuRQtdTK_5gb8ik16fvZ1VvSEPtsTJ