apiVersion: gateway.networking.k8s.io/v1
kind: httproute
metadata:
  name: keycloak-http-route
  namespace: keycloak
spec:
  gatewayClassName: ngrok
  listeners:
  - name: http-listener
    port: 80
    protocol: HTTP
    hostname: keycloak.ryanguild.xyz
  hostnames:
    - keycloak.ryanguild.xyz
  parentRefs:
    - name: ngrok
      namespace: ngrok
  rules:
    - matches:
      - path:
          type: PathPrefix
          value: /