apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: keycloak-http-route
spec:
  hostnames:
    - keycloak.ryanguild.xyz
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: ngrok-gateway
      namespace: ngrok
  rules:
    - backendRefs:
        - kind: Service
          name: keycloak
          port: 80