apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: keycloak-http-route
spec:
  hostnames:
    - keycloak.ryanguild.xyz
  parentRefs:
    - name: ngrok-gateway
      namespace: ngrok
  rules:
    - matches:
      - backendRefs:
          - name: keycloak
            port: 80