apiVersion: v1
kind: service
metadata:
  name: argocd-server
  namespace: default
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: https
      port: 443
      targetPort: 8443
  selector:
    app.kubernetes.io/name: argocd-server
  type: LoadBalancer
