apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
spec:
  project: xyz
  sources:
    - repoURL: ghcr.io/nginxinc/charts
      chart: nginx-gateway-fabric
      targetRevision: 1.5.1
    - repoURL: https://github.com/ryanguild/xyz-cluster.git
      targetRevision: main
      path: nginx/src
    - repoURL: https://github.com/kubernetes-sigs/gateway-api
      targetRevision: v1.2.0
      path: config/crd/experimental
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true