apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
spec:
  project: xyz
  sources:
    - repoURL: ghcr.io/nginx/charts
      chart: nginx-gateway-fabric
      targetRevision: 1.6.2
    - repoURL: https://github.com/ryanguild/xyz-cluster.git
      targetRevision: main
      path: nginx/src
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true