apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: default
spec:
  project: xyz
  sources:
    # - repoURL: https://argoproj.github.io/argo-helm
    #   targetRevision: 7.7.16
    #   chart: argo-cd
    #   kustomize:
    #     patches:
    #       - target:
    #           kind: ConfigMap
    #           name: argocd-cm
    #           namespace: default
    #           version: v1
    #         patch: |-
    #           - op: replace
    #             path: /data/url
    #             value: https://argocd.ryanguild.localhost

    #       patch: argocd/patches/argocd-cm.yaml
    - repoURL: https://github.com/ryanguild/xyz-cluster.git
      targetRevision: main
      path: argocd/src
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
