apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: xyz
  sources:
  - repoURL: https://argoproj.github.io/argo-helm
    targetRevision: main
    chart: argo-cd
  
