apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: default
spec:
  project: xyz
  sources:
    - repoURL: https://github.com/ryanguild/xyz-cluster.git
      targetRevision: main
      path: argocd/src
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
