apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: argocd
spec:
  project: xyz
  sources:
  - repoURL: "https://argoproj.github.io/argo-helm"
    chart: "argo-workflows"
    targetRevision: ">=0.26.0"
    helm:
      releaseName: "argo-workflows"
  - repoURL: https://github.com/RyanGuild/xyz-cluster.git
    path: argo/src
    targetRevision: main
  destination:
    server: "https://kubernetes.default.svc"
    namespace: xyz
  syncPolicy:
    automated:
      prune: true
      selfHeal: true