apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: certmanager
  namespace: default
spec:
  project: xyz
  sources:
    - repoURL: https://charts.jetstack.io
      chart: cert-manager
      targetRevision: 1.16.3
      helm:
        releaseName: cert-manager
        valuesObject:
          crds:
            create: true

  destination:
    server: https://kubernetes.default.svc
    namespace: default
