apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: certmanager
  namespace: default
spec:
  project: xyz
  sources:
    - repoURL: https://charts.jetstack.io
      chart: cert-manager
      targetRevision: 1.16.3
      helm:
        releaseName: cert-manager
        valuesObject:
          crds:
            enabled: true
        parameters:
          - crds:
              enabled: true
    - repoURL: https://github.com/ryanguild/xyz-cluster
      targetRevision: main
      path: certmanager/src

  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
