apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gateway-tls-cert
  namespace: ngrok
spec:
  secretName: gateway-tls-cert-secret
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  commonName: ryanguild.xyz
  dnsNames:
    - ryanguild.xyz
    - "*.ryanguild.xyz"
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer