apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: ngrok-gateway
  namespace: ngrok
spec:
  gatewayClassName: ngrok-gateway-class
  listeners:
    - name: web
      protocol: HTTP
      port: 80  
      hostname: ryanguild.xyz
      allowedRoutes:
        kinds:
          - group: gateway.networking.k8s.io
            kind: HTTPRoute
        namespaces:
          from: All
    - name: websecure
      protocol: HTTPS
      port: 443
      hostname: ryanguild.xyz
      allowedRoutes:
        kinds:
          - group: gateway.networking.k8s.io
            kind: HTTPRoute
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - name: gateway-tls-cert-secret
            namespace: ngrok
    

  