apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: ngrok-gateway
  namespace: ngrok
spec:
  gatewayClassName: ngrok-gateway-class
  listeners:
    - name: ngrok-web
      protocol: HTTP
      port: 80  
      hostname: ryanguild.xyz
      allowedRoutes:
        kinds:
          - kind: HTTPRoute
        namespaces:
          from: All
          to: All
    

  