apiVersion: ingress.k8s.ngrok.com/v1alpha1
kind: Edge
metadata:
  name: hello-edge
  namespace: xyz
spec:
  hostports:
    - ryanguild.xyz.ngrok.app
  type: https
  routes:
    - backend:
        service:
          name: hello-backend
          port: 80 