apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: xyz
  sources:
  - repoURL: https://github.com/ryanguild/xyz-cluster.git
    targetRevision: main
    path: cert-manager/src
  - repoURL: 'https://charts.jetstack.io'
    chart: cert-manager
    targetRevision: v1.17.1
    helm:
      parameters:
      valuesObject:
        installCRDs: true
        namespace: cert-manager
        fullnameOverride: cert-manager
        extraArgs:
          - --enable-gateway-api
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true